name: YouTube Analytics Cronjob

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code...
        uses: actions/checkout@v4

      - name: Setting up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Running script...
        env:
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: npx tsx src/scripts/fetch_data.ts
